name: Gerar animação da cobrinha

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gerar animação da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#39d353&snake_growing=true
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#39d353&snake_growing=true

      - name: Enviar animação para o branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}